BEGIN;
CREATE EXTENSION IF NOT EXISTS pgtap WITH SCHEMA extensions;
SET LOCAL search_path = public, extensions;
SELECT plan(10);
SELECT has_table('public', 'orders', 'orders table exists');
SELECT has_function('public', 'place_order', ARRAY['text', 'numeric', 'numeric', 'text', 'jsonb'], 'atomic creation RPC exists');
SELECT is((SELECT count(*)::int FROM public.menu_items), 4, 'four synthetic menu variants');
SELECT is((SELECT count(*)::int FROM public.profiles WHERE email LIKE '%@patanos.test'), 2, 'synthetic staff accounts only');
SELECT is((SELECT role::text FROM public.profiles WHERE id = '11111111-1111-4111-8111-111111111111'), 'admin', 'admin fixture');
SELECT is((SELECT role::text FROM public.profiles WHERE id = '22222222-2222-4222-8222-222222222222'), 'cashier', 'cashier fixture');
SELECT is((SELECT stock_count FROM public.inventory WHERE menu_item_id = 104), 0, 'sold-out portion fixture');
SELECT ok((SELECT relrowsecurity FROM pg_class WHERE oid = 'public.profiles'::regclass), 'profiles RLS enabled, not proof of safe policy');
SET LOCAL ROLE authenticated;
SELECT set_config('request.jwt.claim.sub', '22222222-2222-4222-8222-222222222222', true);
SELECT is(public.get_user_role()::text, 'cashier', 'cashier fixture through authenticated role helper');
SELECT set_config('request.jwt.claim.sub', '11111111-1111-4111-8111-111111111111', true);
SELECT is(public.get_user_role()::text, 'admin', 'admin fixture through authenticated role helper');
RESET ROLE;
SELECT * FROM finish();
ROLLBACK;
