import { useState, useCallback, useEffect, useRef } from 'react'
import { Alert } from 'react-native'
import { supabase } from '@/src/lib/supabase'
import { useAuth } from '@/src/contexts/AuthContext'
import { useNetworkStatus } from '@/src/hooks/useNetworkStatus'
import { enqueue, getQueue, syncQueue } from '@/src/lib/offlineQueue'

export function useOrders() {
  const { session } = useAuth()
  const { isOnline, onStatusChange } = useNetworkStatus()
  const [openOrders, setOpenOrders] = useState([])
  const [completedOrders, setCompletedOrders] = useState([])
  const [queuedOrders, setQueuedOrders] = useState([])
  const [pendingCount, setPendingCount] = useState(0)
  const [loading, setLoading] = useState(true)
  const syncing = useRef(false)

  const todayStart = () => {
    const d = new Date()
    d.setHours(0, 0, 0, 0)
    return d.toISOString()
  }

  const fetchOrders = useCallback(async () => {
    const start = todayStart()

    const [openRes, completedRes] = await Promise.all([
      supabase
        .from('orders')
        .select('*, order_items(*, order_item_modifiers(*))')
        .eq('status', 'open')
        .gte('created_at', start)
        .order('created_at', { ascending: false }),
      supabase
        .from('orders')
        .select('*, order_items(*, order_item_modifiers(*))')
        .eq('status', 'completed')
        .gte('created_at', start)
        .order('completed_at', { ascending: false })
        .limit(50),
    ])

    if (openRes.data) setOpenOrders(openRes.data)
    if (completedRes.data) setCompletedOrders(completedRes.data)
    setLoading(false)
  }, [])

  useEffect(() => {
    fetchOrders()

    const channel = supabase
      .channel('orders-realtime')
      .on(
        'postgres_changes',
        { event: '*', schema: 'public', table: 'orders' },
        () => fetchOrders(),
      )
      .subscribe()

    return () => { supabase.removeChannel(channel) }
  }, [fetchOrders])

  /**
   * Place a new order directly to Supabase (internal, always online).
   */
  const _placeOrderOnline = async ({ items, orderType, subtotal, notes }) => {
    const userId = session?.user?.id
    if (!userId) return { data: null, error: 'Not authenticated' }

    // 1. Insert order (order_number auto-generated by trigger)
    const { data: order, error: orderErr } = await supabase
      .from('orders')
      .insert({
        order_type: orderType,
        subtotal: subtotal,
        total_amount: subtotal, // no discount for now
        notes: notes || null,
        created_by: userId,
      })
      .select()
      .single()

    if (orderErr) return { data: null, error: orderErr.message }

    // 2. Insert order items
    const orderItems = items.map(item => ({
      order_id: order.id,
      menu_item_id: item.menu_item_id,
      item_name: item.item_name,
      size_label: item.size_label,
      quantity: item.quantity,
      unit_price: item.unit_price,
      notes: item.notes || null,
    }))

    const { data: insertedItems, error: itemsErr } = await supabase
      .from('order_items')
      .insert(orderItems)
      .select()

    if (itemsErr) return { data: order, error: itemsErr.message }

    // 3. Insert modifiers for each order item
    const modRows = []
    items.forEach((cartItem, idx) => {
      if (cartItem.modifiers?.length && insertedItems?.[idx]) {
        cartItem.modifiers.forEach(mod => {
          modRows.push({
            order_item_id: insertedItems[idx].id,
            modifier_id: mod.id,
            modifier_name: mod.modifier_name,
            extra_price: mod.extra_price,
          })
        })
      }
    })

    if (modRows.length > 0) {
      const { error: modErr } = await supabase
        .from('order_item_modifiers')
        .insert(modRows)

      if (modErr) console.warn('Failed to save modifiers:', modErr.message)
    }

    return { data: order, error: null }
  }

  /**
   * Place order — queues locally if offline, otherwise sends to Supabase.
   */
  const placeOrder = async ({ items, orderType, subtotal, notes }) => {
    if (isOnline) {
      return _placeOrderOnline({ items, orderType, subtotal, notes })
    }

    // Offline — queue locally
    const count = await enqueue({ items, orderType, subtotal, notes })
    setPendingCount(count)
    await refreshQueuedOrders()
    return {
      data: { order_number: `Q${count}`, offline: true },
      error: null,
    }
  }

  // Load queued orders from AsyncStorage
  const refreshQueuedOrders = useCallback(async () => {
    const queue = await getQueue()
    setPendingCount(queue.length)
    // Convert queue items to a shape similar to real orders for display
    setQueuedOrders(queue.map((q, idx) => ({
      id: q.id,
      order_number: `Q${idx + 1}`,
      offline: true,
      order_type: q.orderType,
      total_amount: q.subtotal,
      created_at: q.queuedAt,
      status: 'queued',
      order_items: q.items.map(item => ({
        id: item.cartId,
        item_name: item.item_name,
        size_label: item.size_label,
        quantity: item.quantity,
        unit_price: item.unit_price,
        notes: item.notes,
        order_item_modifiers: (item.modifiers || []).map(m => ({
          id: m.id,
          modifier_name: m.modifier_name,
          extra_price: m.extra_price,
        })),
      })),
    })))
  }, [])

  // Refresh pending count and queued orders on mount
  useEffect(() => {
    refreshQueuedOrders()
  }, [])

  // Auto-sync queued orders when coming back online
  const trySyncQueue = useCallback(async () => {
    if (syncing.current || !session?.user?.id) return
    syncing.current = true
    try {
      const queue = await getQueue()
      if (queue.length === 0) {
        syncing.current = false
        await refreshQueuedOrders()
        return
      }
      const { synced, failed } = await syncQueue(_placeOrderOnline)
      await refreshQueuedOrders()
      if (synced > 0) {
        Alert.alert(
          'Orders Synced',
          `${synced} offline order${synced > 1 ? 's' : ''} synced successfully.${failed > 0 ? ` ${failed} failed and will retry.` : ''}`,
        )
        fetchOrders()
      }
    } catch (e) {
      console.warn('Sync failed:', e)
    }
    syncing.current = false
  }, [session, fetchOrders, refreshQueuedOrders])

  // Only trigger sync from onStatusChange (single listener, no duplication)
  useEffect(() => {
    return onStatusChange((online) => {
      if (online) trySyncQueue()
    })
  }, [onStatusChange, trySyncQueue])

  /**
   * Complete an order (collect payment).
   */
  const completeOrder = async ({ orderId, paymentMethod, amountTendered, changeAmount, paymentRef }) => {
    const { error } = await supabase
      .from('orders')
      .update({
        status: 'completed',
        payment_method: paymentMethod,
        amount_tendered: amountTendered || null,
        change_amount: changeAmount || null,
        payment_ref: paymentRef || null,
        completed_at: new Date().toISOString(),
      })
      .eq('id', orderId)

    if (error) {
      Alert.alert('Error', error.message)
      return { error: error.message }
    }
    return { error: null }
  }

  /**
   * Cancel an order.
   */
  const cancelOrder = async (orderId, reason = '') => {
    const { error } = await supabase
      .from('orders')
      .update({
        status: 'cancelled',
        cancelled_at: new Date().toISOString(),
        cancel_reason: reason || null,
      })
      .eq('id', orderId)

    if (error) {
      Alert.alert('Error', error.message)
      return { error: error.message }
    }
    return { error: null }
  }

  return {
    openOrders,
    completedOrders,
    queuedOrders,
    loading,
    isOnline,
    pendingCount,
    placeOrder,
    completeOrder,
    cancelOrder,
    refresh: fetchOrders,
    syncNow: trySyncQueue,
  }
}
