import { useState, useCallback, useEffect } from 'react'
import { Alert } from 'react-native'
import { supabase } from '@/src/lib/supabase'
import { useAuth } from '@/src/contexts/AuthContext'

export function useOrders() {
  const { session } = useAuth()
  const [openOrders, setOpenOrders] = useState([])
  const [completedOrders, setCompletedOrders] = useState([])
  const [loading, setLoading] = useState(true)

  const todayStart = () => {
    const d = new Date()
    d.setHours(0, 0, 0, 0)
    return d.toISOString()
  }

  const fetchOrders = useCallback(async () => {
    const start = todayStart()

    const [openRes, completedRes] = await Promise.all([
      supabase
        .from('orders')
        .select('*, order_items(*, order_item_modifiers(*))')
        .eq('status', 'open')
        .gte('created_at', start)
        .order('created_at', { ascending: false }),
      supabase
        .from('orders')
        .select('*, order_items(*, order_item_modifiers(*))')
        .eq('status', 'completed')
        .gte('created_at', start)
        .order('completed_at', { ascending: false })
        .limit(50),
    ])

    if (openRes.data) setOpenOrders(openRes.data)
    if (completedRes.data) setCompletedOrders(completedRes.data)
    setLoading(false)
  }, [])

  useEffect(() => {
    fetchOrders()

    const channel = supabase
      .channel('orders-realtime')
      .on(
        'postgres_changes',
        { event: '*', schema: 'public', table: 'orders' },
        () => fetchOrders(),
      )
      .subscribe()

    return () => { supabase.removeChannel(channel) }
  }, [fetchOrders])

  /**
   * Place a new order.
   * @param {object} params
   * @param {Array} params.items - cart items from CartContext
   * @param {string} params.orderType - 'dine-in' or 'takeout'
   * @param {number} params.subtotal
   * @param {string} [params.notes]
   * @returns {{ data: object|null, error: string|null }}
   */
  const placeOrder = async ({ items, orderType, subtotal, notes }) => {
    const userId = session?.user?.id
    if (!userId) return { data: null, error: 'Not authenticated' }

    // 1. Insert order (order_number auto-generated by trigger)
    const { data: order, error: orderErr } = await supabase
      .from('orders')
      .insert({
        order_type: orderType,
        subtotal: subtotal,
        total_amount: subtotal, // no discount for now
        notes: notes || null,
        created_by: userId,
      })
      .select()
      .single()

    if (orderErr) return { data: null, error: orderErr.message }

    // 2. Insert order items
    const orderItems = items.map(item => ({
      order_id: order.id,
      menu_item_id: item.menu_item_id,
      item_name: item.item_name,
      size_label: item.size_label,
      quantity: item.quantity,
      unit_price: item.unit_price,
      notes: item.notes || null,
    }))

    const { data: insertedItems, error: itemsErr } = await supabase
      .from('order_items')
      .insert(orderItems)
      .select()

    if (itemsErr) return { data: order, error: itemsErr.message }

    // 3. Insert modifiers for each order item
    const modRows = []
    items.forEach((cartItem, idx) => {
      if (cartItem.modifiers?.length && insertedItems?.[idx]) {
        cartItem.modifiers.forEach(mod => {
          modRows.push({
            order_item_id: insertedItems[idx].id,
            modifier_id: mod.id,
            modifier_name: mod.modifier_name,
            extra_price: mod.extra_price,
          })
        })
      }
    })

    if (modRows.length > 0) {
      const { error: modErr } = await supabase
        .from('order_item_modifiers')
        .insert(modRows)

      if (modErr) console.warn('Failed to save modifiers:', modErr.message)
    }

    return { data: order, error: null }
  }

  /**
   * Complete an order (collect payment).
   */
  const completeOrder = async ({ orderId, paymentMethod, amountTendered, changeAmount, paymentRef }) => {
    const { error } = await supabase
      .from('orders')
      .update({
        status: 'completed',
        payment_method: paymentMethod,
        amount_tendered: amountTendered || null,
        change_amount: changeAmount || null,
        payment_ref: paymentRef || null,
        completed_at: new Date().toISOString(),
      })
      .eq('id', orderId)

    if (error) {
      Alert.alert('Error', error.message)
      return { error: error.message }
    }
    return { error: null }
  }

  /**
   * Cancel an order.
   */
  const cancelOrder = async (orderId, reason = '') => {
    const { error } = await supabase
      .from('orders')
      .update({
        status: 'cancelled',
        cancelled_at: new Date().toISOString(),
        cancel_reason: reason || null,
      })
      .eq('id', orderId)

    if (error) {
      Alert.alert('Error', error.message)
      return { error: error.message }
    }
    return { error: null }
  }

  return {
    openOrders,
    completedOrders,
    loading,
    placeOrder,
    completeOrder,
    cancelOrder,
    refresh: fetchOrders,
  }
}
