-- P0.2 reconstruction for EMPTY LOCAL Supabase only; NOT a production migration.

-- Source: reviewed export 2026-10-04; SHA-256 845638c64e5a5f0c4bc3d81343a44d9eec591f2ad4f8aa279ec540b117a6ead2

-- Retains known P1/P2/P4 permission and transaction defects for regression work.

-- Snapshot omits numeric typmods, identity generation mode and Realtime publication.

-- Uses unbounded numeric and BY DEFAULT identities; qualify against an authorized dump.

-- Managed auth/storage tables are supplied by Supabase, never recreated here.

BEGIN;

SET LOCAL search_path = public, extensions;

CREATE TYPE public."item_status" AS ENUM ('published', 'draft', 'archived');

CREATE TYPE public."order_status" AS ENUM ('open', 'completed', 'cancelled');

CREATE TYPE public."order_type" AS ENUM ('dine-in', 'takeout', 'delivery');

CREATE TYPE public."payment_method" AS ENUM ('cash', 'gcash');

CREATE TYPE public."user_role" AS ENUM ('admin', 'cashier');

CREATE TABLE public."categories" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "name" text NOT NULL,
  "slug" text NOT NULL,
  "icon" text,
  "sort_order" integer DEFAULT 0 NOT NULL,
  "status" public."item_status" DEFAULT 'published'::item_status NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public."gallery_photos" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "image_url" text NOT NULL,
  "caption" text DEFAULT ''::text NOT NULL,
  "link_url" text,
  "sort_order" integer DEFAULT 0 NOT NULL,
  "status" public."item_status" DEFAULT 'published'::item_status NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public."inventory" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "menu_item_id" bigint NOT NULL,
  "stock_count" integer DEFAULT 0 NOT NULL,
  "low_stock_threshold" integer DEFAULT 10 NOT NULL,
  "track_inventory" boolean DEFAULT false NOT NULL,
  "last_restocked_at" timestamp with time zone,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public."menu_items" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" text NOT NULL,
  "description" text,
  "price" numeric NOT NULL,
  "size_label" text,
  "category_id" uuid NOT NULL,
  "image_url" text,
  "status" public."item_status" DEFAULT 'published'::item_status NOT NULL,
  "is_featured" boolean DEFAULT false NOT NULL,
  "available" boolean DEFAULT true NOT NULL,
  "sort_order" integer DEFAULT 0 NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public."modifier_groups" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" text NOT NULL,
  "category_id" uuid,
  "menu_item_id" bigint,
  "min_select" integer DEFAULT 0 NOT NULL,
  "max_select" integer,
  "sort_order" integer DEFAULT 0 NOT NULL,
  "status" public."item_status" DEFAULT 'published'::item_status NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public."modifiers" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "modifier_group_id" bigint NOT NULL,
  "name" text NOT NULL,
  "extra_price" numeric DEFAULT 0 NOT NULL,
  "available" boolean DEFAULT true NOT NULL,
  "sort_order" integer DEFAULT 0 NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public."order_item_modifiers" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "order_item_id" bigint NOT NULL,
  "modifier_id" bigint NOT NULL,
  "modifier_name" text NOT NULL,
  "extra_price" numeric DEFAULT 0 NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public."order_items" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "order_id" bigint NOT NULL,
  "menu_item_id" bigint NOT NULL,
  "item_name" text NOT NULL,
  "size_label" text,
  "quantity" integer DEFAULT 1 NOT NULL,
  "unit_price" numeric NOT NULL,
  "subtotal" numeric GENERATED ALWAYS AS (((quantity)::numeric * unit_price)) STORED,
  "notes" text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public."orders" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "order_number" text NOT NULL,
  "order_type" public."order_type" DEFAULT 'dine-in'::order_type NOT NULL,
  "status" public."order_status" DEFAULT 'open'::order_status NOT NULL,
  "subtotal" numeric DEFAULT 0 NOT NULL,
  "discount_amount" numeric DEFAULT 0 NOT NULL,
  "total_amount" numeric DEFAULT 0 NOT NULL,
  "payment_method" public."payment_method",
  "payment_ref" text,
  "amount_tendered" numeric,
  "change_amount" numeric,
  "notes" text,
  "created_by" uuid NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "completed_at" timestamp with time zone,
  "cancelled_at" timestamp with time zone,
  "cancel_reason" text
);

CREATE TABLE public."profiles" (
  "id" uuid NOT NULL,
  "email" text NOT NULL,
  "full_name" text,
  "role" public."user_role" DEFAULT 'cashier'::user_role NOT NULL,
  "avatar_url" text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public."categories" ADD CONSTRAINT "categories_pkey" PRIMARY KEY (id);

ALTER TABLE public."categories" ADD CONSTRAINT "categories_slug_key" UNIQUE (slug);

ALTER TABLE public."gallery_photos" ADD CONSTRAINT "gallery_photos_pkey" PRIMARY KEY (id);

ALTER TABLE public."inventory" ADD CONSTRAINT "inventory_menu_item_id_key" UNIQUE (menu_item_id);

ALTER TABLE public."inventory" ADD CONSTRAINT "inventory_pkey" PRIMARY KEY (id);

ALTER TABLE public."inventory" ADD CONSTRAINT "inventory_stock_count_check" CHECK (stock_count >= 0);

ALTER TABLE public."menu_items" ADD CONSTRAINT "menu_items_pkey" PRIMARY KEY (id);

ALTER TABLE public."menu_items" ADD CONSTRAINT "menu_items_price_check" CHECK (price >= 0::numeric);

ALTER TABLE public."modifier_groups" ADD CONSTRAINT "modifier_group_target" CHECK (NOT (category_id IS NOT NULL AND menu_item_id IS NOT NULL));

ALTER TABLE public."modifier_groups" ADD CONSTRAINT "modifier_groups_max_select_check" CHECK (max_select IS NULL OR max_select >= 1);

ALTER TABLE public."modifier_groups" ADD CONSTRAINT "modifier_groups_min_select_check" CHECK (min_select >= 0);

ALTER TABLE public."modifier_groups" ADD CONSTRAINT "modifier_groups_pkey" PRIMARY KEY (id);

ALTER TABLE public."modifiers" ADD CONSTRAINT "modifiers_extra_price_check" CHECK (extra_price >= 0::numeric);

ALTER TABLE public."modifiers" ADD CONSTRAINT "modifiers_pkey" PRIMARY KEY (id);

ALTER TABLE public."order_item_modifiers" ADD CONSTRAINT "modifiers_extra_price_positive" CHECK (extra_price >= 0::numeric);

ALTER TABLE public."order_item_modifiers" ADD CONSTRAINT "order_item_modifiers_pkey" PRIMARY KEY (id);

ALTER TABLE public."order_items" ADD CONSTRAINT "order_items_pkey" PRIMARY KEY (id);

ALTER TABLE public."order_items" ADD CONSTRAINT "order_items_price_positive" CHECK (unit_price >= 0::numeric);

ALTER TABLE public."order_items" ADD CONSTRAINT "order_items_quantity_check" CHECK (quantity > 0);

ALTER TABLE public."order_items" ADD CONSTRAINT "order_items_quantity_positive" CHECK (quantity >= 1);

ALTER TABLE public."order_items" ADD CONSTRAINT "order_items_unit_price_check" CHECK (unit_price >= 0::numeric);

ALTER TABLE public."orders" ADD CONSTRAINT "orders_discount_amount_check" CHECK (discount_amount >= 0::numeric);

ALTER TABLE public."orders" ADD CONSTRAINT "orders_order_type_check" CHECK (order_type = ANY (ARRAY['dine-in'::order_type, 'takeout'::order_type, 'delivery'::order_type]));

ALTER TABLE public."orders" ADD CONSTRAINT "orders_payment_method_check" CHECK (payment_method IS NULL OR (payment_method = ANY (ARRAY['cash'::payment_method, 'gcash'::payment_method])));

ALTER TABLE public."orders" ADD CONSTRAINT "orders_pkey" PRIMARY KEY (id);

ALTER TABLE public."orders" ADD CONSTRAINT "orders_status_check" CHECK (status = ANY (ARRAY['open'::order_status, 'completed'::order_status, 'cancelled'::order_status]));

ALTER TABLE public."orders" ADD CONSTRAINT "orders_subtotal_check" CHECK (subtotal >= 0::numeric);

ALTER TABLE public."orders" ADD CONSTRAINT "orders_subtotal_positive" CHECK (subtotal >= 0::numeric);

ALTER TABLE public."orders" ADD CONSTRAINT "orders_total_amount_check" CHECK (total_amount >= 0::numeric);

ALTER TABLE public."orders" ADD CONSTRAINT "orders_total_positive" CHECK (total_amount >= 0::numeric);

ALTER TABLE public."profiles" ADD CONSTRAINT "profiles_pkey" PRIMARY KEY (id);

ALTER TABLE public."inventory" ADD CONSTRAINT "inventory_menu_item_id_fkey" FOREIGN KEY (menu_item_id) REFERENCES menu_items(id) ON DELETE CASCADE;

ALTER TABLE public."menu_items" ADD CONSTRAINT "menu_items_category_id_fkey" FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE RESTRICT;

ALTER TABLE public."modifier_groups" ADD CONSTRAINT "modifier_groups_category_id_fkey" FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE;

ALTER TABLE public."modifier_groups" ADD CONSTRAINT "modifier_groups_menu_item_id_fkey" FOREIGN KEY (menu_item_id) REFERENCES menu_items(id) ON DELETE CASCADE;

ALTER TABLE public."modifiers" ADD CONSTRAINT "modifiers_modifier_group_id_fkey" FOREIGN KEY (modifier_group_id) REFERENCES modifier_groups(id) ON DELETE CASCADE;

ALTER TABLE public."order_item_modifiers" ADD CONSTRAINT "order_item_modifiers_modifier_id_fkey" FOREIGN KEY (modifier_id) REFERENCES modifiers(id) ON DELETE RESTRICT;

ALTER TABLE public."order_item_modifiers" ADD CONSTRAINT "order_item_modifiers_order_item_id_fkey" FOREIGN KEY (order_item_id) REFERENCES order_items(id) ON DELETE CASCADE;

ALTER TABLE public."order_items" ADD CONSTRAINT "order_items_menu_item_id_fkey" FOREIGN KEY (menu_item_id) REFERENCES menu_items(id) ON DELETE RESTRICT;

ALTER TABLE public."order_items" ADD CONSTRAINT "order_items_order_id_fkey" FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE;

ALTER TABLE public."orders" ADD CONSTRAINT "orders_created_by_fkey" FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE RESTRICT;

ALTER TABLE public."profiles" ADD CONSTRAINT "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;

CREATE INDEX idx_categories_sort ON public.categories USING btree (sort_order);

CREATE INDEX idx_categories_status ON public.categories USING btree (status);

CREATE INDEX idx_gallery_sort ON public.gallery_photos USING btree (sort_order);

CREATE INDEX idx_gallery_status ON public.gallery_photos USING btree (status);

CREATE INDEX idx_inventory_low_stock ON public.inventory USING btree (stock_count) WHERE (track_inventory = true);

CREATE INDEX idx_menu_items_available ON public.menu_items USING btree (available);

CREATE INDEX idx_menu_items_category ON public.menu_items USING btree (category_id);

CREATE INDEX idx_menu_items_featured ON public.menu_items USING btree (is_featured) WHERE (is_featured = true);

CREATE INDEX idx_menu_items_sort ON public.menu_items USING btree (category_id, sort_order, name);

CREATE INDEX idx_menu_items_status ON public.menu_items USING btree (status);

CREATE INDEX idx_modifier_groups_category ON public.modifier_groups USING btree (category_id) WHERE (category_id IS NOT NULL);

CREATE INDEX idx_modifier_groups_menu_item ON public.modifier_groups USING btree (menu_item_id) WHERE (menu_item_id IS NOT NULL);

CREATE INDEX idx_modifier_groups_status ON public.modifier_groups USING btree (status);

CREATE INDEX idx_modifiers_available ON public.modifiers USING btree (available);

CREATE INDEX idx_modifiers_group ON public.modifiers USING btree (modifier_group_id);

CREATE INDEX idx_order_item_modifiers_modifier ON public.order_item_modifiers USING btree (modifier_id);

CREATE INDEX idx_order_item_modifiers_order_item ON public.order_item_modifiers USING btree (order_item_id);

CREATE INDEX idx_order_items_menu_item ON public.order_items USING btree (menu_item_id);

CREATE INDEX idx_order_items_order ON public.order_items USING btree (order_id);

CREATE INDEX idx_orders_created_at ON public.orders USING btree (created_at DESC);

CREATE INDEX idx_orders_created_by ON public.orders USING btree (created_by);

CREATE INDEX idx_orders_daily ON public.orders USING btree (created_at, order_number);

CREATE INDEX idx_orders_status ON public.orders USING btree (status);

CREATE OR REPLACE FUNCTION public.decrement_stock()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  update public.inventory
  set stock_count = greatest(stock_count - new.quantity, 0)
  where menu_item_id = new.menu_item_id
    and track_inventory = true;
  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.generate_order_number()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
declare
  today_count integer;
begin
  select count(*) + 1 into today_count
  from public.orders
  where created_at::date = current_date;

  new.order_number := lpad(today_count::text, 3, '0');
  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.get_user_role()
 RETURNS user_role
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
  select role from public.profiles where id = auth.uid();
$function$;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  insert into public.profiles (id, email, full_name)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'full_name', '')
  );
  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.place_order(p_order_type text, p_subtotal numeric, p_total_amount numeric, p_notes text DEFAULT NULL::text, p_items jsonb DEFAULT '[]'::jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_user_id uuid;
  v_order orders%ROWTYPE;
  v_item jsonb;
  v_inserted_item_id bigint;
  v_modifier jsonb;
  v_result jsonb;
BEGIN
  -- Get the authenticated user
  v_user_id := auth.uid();
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  -- Validate order type
  IF p_order_type NOT IN ('dine-in', 'takeout', 'delivery') THEN
    RAISE EXCEPTION 'Invalid order type: %', p_order_type;
  END IF;

  -- Validate amounts
  IF p_subtotal < 0 OR p_total_amount < 0 THEN
    RAISE EXCEPTION 'Amounts cannot be negative';
  END IF;

  -- Validate items array
  IF jsonb_array_length(p_items) = 0 THEN
    RAISE EXCEPTION 'Order must have at least one item';
  END IF;

  -- 1. Insert order (order_number auto-generated by existing trigger)
  INSERT INTO orders (order_type, subtotal, total_amount, notes, created_by)
  VALUES (p_order_type::order_type, p_subtotal, p_total_amount, p_notes, v_user_id)
  RETURNING * INTO v_order;

  -- 2. Insert order items and their modifiers
  FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
  LOOP
    -- Validate individual item
    IF (v_item->>'quantity')::int < 1 THEN
      RAISE EXCEPTION 'Invalid quantity for item: %', v_item->>'item_name';
    END IF;
    IF (v_item->>'unit_price')::numeric < 0 THEN
      RAISE EXCEPTION 'Invalid price for item: %', v_item->>'item_name';
    END IF;

    INSERT INTO order_items (order_id, menu_item_id, item_name, size_label, quantity, unit_price, notes)
    VALUES (
      v_order.id,
      (v_item->>'menu_item_id')::bigint,
      v_item->>'item_name',
      v_item->>'size_label',
      (v_item->>'quantity')::int,
      (v_item->>'unit_price')::numeric,
      v_item->>'notes'
    )
    RETURNING id INTO v_inserted_item_id;

    -- 3. Insert modifiers for this item
    IF v_item ? 'modifiers' AND jsonb_array_length(v_item->'modifiers') > 0 THEN
      FOR v_modifier IN SELECT * FROM jsonb_array_elements(v_item->'modifiers')
      LOOP
        INSERT INTO order_item_modifiers (order_item_id, modifier_id, modifier_name, extra_price)
        VALUES (
          v_inserted_item_id,
          (v_modifier->>'id')::bigint,
          v_modifier->>'modifier_name',
          (v_modifier->>'extra_price')::numeric
        );
      END LOOP;
    END IF;
  END LOOP;

  -- Return the created order as JSON
  v_result := jsonb_build_object(
    'id', v_order.id,
    'order_number', v_order.order_number,
    'order_type', v_order.order_type,
    'subtotal', v_order.subtotal,
    'total_amount', v_order.total_amount,
    'status', v_order.status,
    'created_at', v_order.created_at
  );

  RETURN v_result;
END;
$function$;

CREATE OR REPLACE FUNCTION public.restore_stock_on_cancel()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  if old.status != 'cancelled' and new.status = 'cancelled' then
    update public.inventory inv
    set stock_count = inv.stock_count + oi.quantity
    from public.order_items oi
    where oi.order_id = new.id
      and inv.menu_item_id = oi.menu_item_id
      and inv.track_inventory = true;
  end if;
  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.update_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  new.updated_at = now();
  return new;
end;
$function$;

CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION handle_new_user();

CREATE TRIGGER categories_updated_at BEFORE UPDATE ON categories FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER gallery_photos_updated_at BEFORE UPDATE ON gallery_photos FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER inventory_updated_at BEFORE UPDATE ON inventory FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER menu_items_updated_at BEFORE UPDATE ON menu_items FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER modifier_groups_updated_at BEFORE UPDATE ON modifier_groups FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER modifiers_updated_at BEFORE UPDATE ON modifiers FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER order_items_decrement_stock AFTER INSERT ON order_items FOR EACH ROW EXECUTE FUNCTION decrement_stock();

CREATE TRIGGER orders_restore_stock_on_cancel AFTER UPDATE ON orders FOR EACH ROW EXECUTE FUNCTION restore_stock_on_cancel();

CREATE TRIGGER orders_set_order_number BEFORE INSERT ON orders FOR EACH ROW WHEN (new.order_number IS NULL OR new.order_number = ''::text) EXECUTE FUNCTION generate_order_number();

CREATE TRIGGER profiles_updated_at BEFORE UPDATE ON profiles FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE VIEW public."category_sales" AS
 SELECT o.created_at::date AS sale_date,
    c.name AS category_name,
    sum(oi.quantity) AS items_sold,
    sum(oi.subtotal) AS revenue
   FROM order_items oi
     JOIN orders o ON o.id = oi.order_id
     JOIN menu_items mi ON mi.id = oi.menu_item_id
     JOIN categories c ON c.id = mi.category_id
  WHERE o.status = 'completed'::order_status
  GROUP BY (o.created_at::date), c.name
  ORDER BY (o.created_at::date) DESC, (sum(oi.subtotal)) DESC;

CREATE VIEW public."daily_sales" AS
 SELECT created_at::date AS sale_date,
    count(*) AS total_orders,
    COALESCE(sum(total_amount), 0::numeric) AS total_revenue,
    COALESCE(avg(total_amount), 0::numeric) AS avg_order_value,
    COALESCE(sum(total_amount) FILTER (WHERE payment_method = 'cash'::payment_method), 0::numeric) AS cash_sales,
    COALESCE(sum(total_amount) FILTER (WHERE payment_method = 'gcash'::payment_method), 0::numeric) AS gcash_sales,
    count(*) FILTER (WHERE order_type = 'dine-in'::order_type) AS dinein_count,
    count(*) FILTER (WHERE order_type = 'takeout'::order_type) AS takeout_count,
    count(*) FILTER (WHERE order_type = 'delivery'::order_type) AS delivery_count
   FROM orders
  WHERE status = 'completed'::order_status
  GROUP BY (created_at::date)
  ORDER BY (created_at::date) DESC;

ALTER TABLE public."categories" ENABLE ROW LEVEL SECURITY;

ALTER TABLE public."gallery_photos" ENABLE ROW LEVEL SECURITY;

ALTER TABLE public."inventory" ENABLE ROW LEVEL SECURITY;

ALTER TABLE public."menu_items" ENABLE ROW LEVEL SECURITY;

ALTER TABLE public."modifier_groups" ENABLE ROW LEVEL SECURITY;

ALTER TABLE public."modifiers" ENABLE ROW LEVEL SECURITY;

ALTER TABLE public."order_item_modifiers" ENABLE ROW LEVEL SECURITY;

ALTER TABLE public."order_items" ENABLE ROW LEVEL SECURITY;

ALTER TABLE public."orders" ENABLE ROW LEVEL SECURITY;

ALTER TABLE public."profiles" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admin can delete categories" ON "public"."categories" AS PERMISSIVE FOR DELETE TO PUBLIC USING ((get_user_role() = 'admin'::user_role));

CREATE POLICY "Admin can insert categories" ON "public"."categories" AS PERMISSIVE FOR INSERT TO PUBLIC WITH CHECK ((get_user_role() = 'admin'::user_role));

CREATE POLICY "Admin can update categories" ON "public"."categories" AS PERMISSIVE FOR UPDATE TO PUBLIC USING ((get_user_role() = 'admin'::user_role));

CREATE POLICY "Authenticated can read all categories" ON "public"."categories" AS PERMISSIVE FOR SELECT TO PUBLIC USING ((auth.uid() IS NOT NULL));

CREATE POLICY "Public can read published categories" ON "public"."categories" AS PERMISSIVE FOR SELECT TO PUBLIC USING ((status = 'published'::item_status));

CREATE POLICY "Admin can delete gallery photos" ON "public"."gallery_photos" AS PERMISSIVE FOR DELETE TO PUBLIC USING ((get_user_role() = 'admin'::user_role));

CREATE POLICY "Admin can insert gallery photos" ON "public"."gallery_photos" AS PERMISSIVE FOR INSERT TO PUBLIC WITH CHECK ((get_user_role() = 'admin'::user_role));

CREATE POLICY "Admin can update gallery photos" ON "public"."gallery_photos" AS PERMISSIVE FOR UPDATE TO PUBLIC USING ((get_user_role() = 'admin'::user_role));

CREATE POLICY "Authenticated can read all gallery photos" ON "public"."gallery_photos" AS PERMISSIVE FOR SELECT TO PUBLIC USING ((auth.uid() IS NOT NULL));

CREATE POLICY "Public can read published gallery photos" ON "public"."gallery_photos" AS PERMISSIVE FOR SELECT TO PUBLIC USING ((status = 'published'::item_status));

CREATE POLICY "Admin can insert inventory" ON "public"."inventory" AS PERMISSIVE FOR INSERT TO PUBLIC WITH CHECK ((get_user_role() = 'admin'::user_role));

CREATE POLICY "Admin can update inventory" ON "public"."inventory" AS PERMISSIVE FOR UPDATE TO PUBLIC USING ((get_user_role() = 'admin'::user_role));

CREATE POLICY "Staff can read inventory" ON "public"."inventory" AS PERMISSIVE FOR SELECT TO PUBLIC USING ((auth.uid() IS NOT NULL));

CREATE POLICY "Admin can delete menu items" ON "public"."menu_items" AS PERMISSIVE FOR DELETE TO PUBLIC USING ((get_user_role() = 'admin'::user_role));

CREATE POLICY "Admin can insert menu items" ON "public"."menu_items" AS PERMISSIVE FOR INSERT TO PUBLIC WITH CHECK ((get_user_role() = 'admin'::user_role));

CREATE POLICY "Admin can update menu items" ON "public"."menu_items" AS PERMISSIVE FOR UPDATE TO PUBLIC USING ((get_user_role() = 'admin'::user_role));

CREATE POLICY "Authenticated can read all menu items" ON "public"."menu_items" AS PERMISSIVE FOR SELECT TO PUBLIC USING ((auth.uid() IS NOT NULL));

CREATE POLICY "Public can read published menu items" ON "public"."menu_items" AS PERMISSIVE FOR SELECT TO PUBLIC USING ((status = 'published'::item_status));

CREATE POLICY "Admin can delete modifier groups" ON "public"."modifier_groups" AS PERMISSIVE FOR DELETE TO PUBLIC USING ((get_user_role() = 'admin'::user_role));

CREATE POLICY "Admin can insert modifier groups" ON "public"."modifier_groups" AS PERMISSIVE FOR INSERT TO PUBLIC WITH CHECK ((get_user_role() = 'admin'::user_role));

CREATE POLICY "Admin can update modifier groups" ON "public"."modifier_groups" AS PERMISSIVE FOR UPDATE TO PUBLIC USING ((get_user_role() = 'admin'::user_role));

CREATE POLICY "Authenticated can read all modifier groups" ON "public"."modifier_groups" AS PERMISSIVE FOR SELECT TO PUBLIC USING ((auth.uid() IS NOT NULL));

CREATE POLICY "Public can read published modifier groups" ON "public"."modifier_groups" AS PERMISSIVE FOR SELECT TO PUBLIC USING ((status = 'published'::item_status));

CREATE POLICY "Admin can delete modifiers" ON "public"."modifiers" AS PERMISSIVE FOR DELETE TO PUBLIC USING ((get_user_role() = 'admin'::user_role));

CREATE POLICY "Admin can insert modifiers" ON "public"."modifiers" AS PERMISSIVE FOR INSERT TO PUBLIC WITH CHECK ((get_user_role() = 'admin'::user_role));

CREATE POLICY "Admin can update modifiers" ON "public"."modifiers" AS PERMISSIVE FOR UPDATE TO PUBLIC USING ((get_user_role() = 'admin'::user_role));

CREATE POLICY "Authenticated can read all modifiers" ON "public"."modifiers" AS PERMISSIVE FOR SELECT TO PUBLIC USING ((auth.uid() IS NOT NULL));

CREATE POLICY "Public can read available modifiers" ON "public"."modifiers" AS PERMISSIVE FOR SELECT TO PUBLIC USING ((EXISTS ( SELECT 1
   FROM modifier_groups mg
  WHERE ((mg.id = modifiers.modifier_group_id) AND (mg.status = 'published'::item_status)))));

CREATE POLICY "Cashier can create order item modifiers" ON "public"."order_item_modifiers" AS PERMISSIVE FOR INSERT TO PUBLIC WITH CHECK ((get_user_role() = ANY (ARRAY['admin'::user_role, 'cashier'::user_role])));

CREATE POLICY "Staff can read order item modifiers" ON "public"."order_item_modifiers" AS PERMISSIVE FOR SELECT TO PUBLIC USING ((auth.uid() IS NOT NULL));

CREATE POLICY "Cashier can create order items" ON "public"."order_items" AS PERMISSIVE FOR INSERT TO PUBLIC WITH CHECK ((get_user_role() = ANY (ARRAY['admin'::user_role, 'cashier'::user_role])));

CREATE POLICY "Staff can read order items" ON "public"."order_items" AS PERMISSIVE FOR SELECT TO PUBLIC USING ((auth.uid() IS NOT NULL));

CREATE POLICY "Admin can read all orders" ON "public"."orders" AS PERMISSIVE FOR SELECT TO PUBLIC USING ((get_user_role() = 'admin'::user_role));

CREATE POLICY "Cashier can create orders" ON "public"."orders" AS PERMISSIVE FOR INSERT TO PUBLIC WITH CHECK (((get_user_role() = ANY (ARRAY['admin'::user_role, 'cashier'::user_role])) AND (created_by = auth.uid())));

CREATE POLICY "Staff can read todays orders" ON "public"."orders" AS PERMISSIVE FOR SELECT TO PUBLIC USING (((auth.uid() IS NOT NULL) AND ((created_at)::date = CURRENT_DATE)));

CREATE POLICY "Staff can update orders" ON "public"."orders" AS PERMISSIVE FOR UPDATE TO PUBLIC USING ((auth.uid() IS NOT NULL));

CREATE POLICY "Admin can read all profiles" ON "public"."profiles" AS PERMISSIVE FOR SELECT TO PUBLIC USING ((get_user_role() = 'admin'::user_role));

CREATE POLICY "Admin can update profiles" ON "public"."profiles" AS PERMISSIVE FOR UPDATE TO PUBLIC USING ((get_user_role() = 'admin'::user_role));

CREATE POLICY "Users can read own profile" ON "public"."profiles" AS PERMISSIVE FOR SELECT TO PUBLIC USING ((id = auth.uid()));

CREATE POLICY "Users can update own profile" ON "public"."profiles" AS PERMISSIVE FOR UPDATE TO PUBLIC USING ((id = auth.uid())) WITH CHECK ((id = auth.uid()));

CREATE POLICY "Admin can delete gallery images" ON "storage"."objects" AS PERMISSIVE FOR DELETE TO PUBLIC USING (((bucket_id = 'gallery-images'::text) AND (get_user_role() = 'admin'::user_role)));

CREATE POLICY "Admin can delete menu images" ON "storage"."objects" AS PERMISSIVE FOR DELETE TO PUBLIC USING (((bucket_id = 'menu-images'::text) AND (get_user_role() = 'admin'::user_role)));

CREATE POLICY "Admin can update gallery images" ON "storage"."objects" AS PERMISSIVE FOR UPDATE TO PUBLIC USING (((bucket_id = 'gallery-images'::text) AND (get_user_role() = 'admin'::user_role)));

CREATE POLICY "Admin can update menu images" ON "storage"."objects" AS PERMISSIVE FOR UPDATE TO PUBLIC USING (((bucket_id = 'menu-images'::text) AND (get_user_role() = 'admin'::user_role)));

CREATE POLICY "Admin can upload gallery images" ON "storage"."objects" AS PERMISSIVE FOR INSERT TO PUBLIC WITH CHECK (((bucket_id = 'gallery-images'::text) AND (get_user_role() = 'admin'::user_role)));

CREATE POLICY "Admin can upload menu images" ON "storage"."objects" AS PERMISSIVE FOR INSERT TO PUBLIC WITH CHECK (((bucket_id = 'menu-images'::text) AND (get_user_role() = 'admin'::user_role)));

CREATE POLICY "Public can read gallery images" ON "storage"."objects" AS PERMISSIVE FOR SELECT TO PUBLIC USING ((bucket_id = 'gallery-images'::text));

CREATE POLICY "Public can read menu images" ON "storage"."objects" AS PERMISSIVE FOR SELECT TO PUBLIC USING ((bucket_id = 'menu-images'::text));

GRANT ALL ON TABLE public."categories" TO anon, authenticated, service_role;

GRANT ALL ON TABLE public."category_sales" TO anon, authenticated, service_role;

GRANT ALL ON TABLE public."daily_sales" TO anon, authenticated, service_role;

GRANT ALL ON TABLE public."gallery_photos" TO anon, authenticated, service_role;

GRANT ALL ON TABLE public."inventory" TO anon, authenticated, service_role;

GRANT ALL ON TABLE public."menu_items" TO anon, authenticated, service_role;

GRANT ALL ON TABLE public."modifier_groups" TO anon, authenticated, service_role;

GRANT ALL ON TABLE public."modifiers" TO anon, authenticated, service_role;

GRANT ALL ON TABLE public."order_item_modifiers" TO anon, authenticated, service_role;

GRANT ALL ON TABLE public."order_items" TO anon, authenticated, service_role;

GRANT ALL ON TABLE public."orders" TO anon, authenticated, service_role;

GRANT ALL ON TABLE public."profiles" TO anon, authenticated, service_role;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;

REVOKE CREATE ON SCHEMA public FROM PUBLIC, anon, authenticated;

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types) VALUES ('gallery-images', 'gallery-images', true, NULL, NULL);

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types) VALUES ('menu-images', 'menu-images', true, NULL, NULL);

-- Realtime publication membership was not exported; qualify separately before enabling.

COMMIT;
